<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
<xsl:output method="html" indent="yes"/>

<xsl:template match="/">
  <html>
  <head>
    <title>Sitemap</title>
    <style>
      body { font-family: sans-serif; margin: 20px; background-color: #171717; color: #FFFFFF; }
      h1 { color: #9E7FFF; }
      table { width: 100%; border-collapse: collapse; margin-top: 20px; background-color: #262626; border-radius: 8px; overflow: hidden; }
      th, td { padding: 12px 15px; text-align: left; border-bottom: 1px solid #2F2F2F; }
      th { background-color: #38bdf8; color: #171717; font-weight: bold; }
      tr:hover { background-color: #2F2F2F; }
      a { color: #f472b6; text-decoration: none; }
      a:hover { text-decoration: underline; }
      .note { font-size: 0.9em; color: #A3A3A3; margin-top: 10px; }
    </style>
  </head>
  <body>
    <h1>Sitemap for LinguaSolutions India</h1>
    <p class="note">This is a human-readable version of your sitemap, generated by an XSL stylesheet. Search engines will parse the raw XML directly.</p>
    <table>
      <thead>
        <tr>
          <th>URL</th>
          <th>Change Frequency</th>
          <th>Priority</th>
          <th>Image</th>
          <th>Image Title</th>
        </tr>
      </thead>
      <tbody>
        <xsl:for-each select="sitemap:urlset/sitemap:url">
          <tr>
            <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
            <td><xsl:value-of select="sitemap:changefreq"/></td>
            <td><xsl:value-of select="sitemap:priority"/></td>
            <td>
              <xsl:if test="image:image/image:loc">
                <a href="{image:image/image:loc}" target="_blank">View Image</a>
              </xsl:if>
            </td>
            <td><xsl:value-of select="image:image/image:title"/></td>
          </tr>
        </xsl:for-each>
      </tbody>
    </table>
  </body>
  </html>
</xsl:template>

</xsl:stylesheet>
