// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grbpdhxqurzttlesapob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyYnBkaHhxdXJ6dHRsZXNhcG9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MjUxNzEsImV4cCI6MjA2NTIwMTE3MX0.Ybh9EyNDVgm6_H7p-tR1BBtyeJVy_RFsxGbP_ZbePTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
